### ISSUE TITLE
Missing definitions in header

### ISSUE THREAD

**Issue by MartijnBraam** [plieningerweb/esp8266-software-uart#11]
I'm not very experienced with C/C++ (at all) but shouldn't these lines be added to the softuart.h?

``` cpp
void Softuart_SetPinRx(Softuart *s, uint8_t gpio_id);
void Softuart_SetPinTx(Softuart *s, uint8_t gpio_id);
void Softuart_EnableRs485(Softuart *s, uint8_t gpio_id);
void Softuart_Init(Softuart *s, uint32_t baudrate);
```

The compiler seems to make it work because other stuff is defined in the header that includes the .c file but the syntax highlighting in clion keeps annoying me that the functions don't exist.

**Comment by plieningerweb** [comment]
closed with merged pull request
