### ISSUE TITLE
issue in Softuart_Putchar

### ISSUE THREAD

**Issue by emichel11** [plieningerweb/esp8266-software-uart#14]
The for loop in Softuart_Putchar has an issue. It runs 9 times instead of 8.
it should read
for(i = 0; i < 8; i ++ )

**Comment by plieningerweb** [comment]
Could you do a pull request?

**Comment by emichel11** [comment]
It seems I do not have the permission to generate a pull request. My push fails.
Here the diff:
324c324
< 	for(i = 0; i <= 8; i ++ )
---
> 	for(i = 0; i < 8; i ++ )

**Comment by emichel11** [comment]
It seems I do not have the permission. My push fails. 
for(i = 0; i <= 8; i ++ ) should be changed to
for(i = 0; i < 8; i ++ )
in line 324

**Comment by plieningerweb** [comment]
Thanks for the issue!

Regarding the pull request: Usually you do first a fork on github, then push to your own repository, then do a pull request to this repository.

Thanks for reporting, let me know if the issue is solved now!
